"""add last activity 2

Revision ID: 00d56ba8fd03
Revises: 5072e1d722aa
Create Date: 2026-06-16 19:58:45.932213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00d56ba8fd03'
down_revision = '5072e1d722aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.alter_column('last_activity_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.alter_column('last_activity_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
