"""add role status ppr and user sessions

Revision ID: 04f2b5feac51
Revises: 21fd9696deeb
Create Date: 2026-06-16 16:53:38.996117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04f2b5feac51'
down_revision = '21fd9696deeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_sertifikat_ppr', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_no_sertifikat_ppr'), ['no_sertifikat_ppr'], unique=False)
        batch_op.drop_column('is_verified')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120), nullable=False))
        batch_op.add_column(sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_no_sertifikat_ppr'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('status')
        batch_op.drop_column('role')
        batch_op.drop_column('no_sertifikat_ppr')

    # ### end Alembic commands ###
