"""initial

Revision ID: 21fd9696deeb
Revises: 
Create Date: 2026-06-16 12:47:29.822428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fd9696deeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('pertanyaan', sa.String(length=255), nullable=False),
    sa.Column('jawaban', sa.Text(), nullable=False),
    sa.Column('dasar_hukum', sa.Text(), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kategori', 'pertanyaan', name='uq_faq_kategori_pertanyaan')
    )
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faq_kategori'), ['kategori'], unique=False)

    op.create_table('panduan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('judul', sa.String(length=150), nullable=False),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kategori', 'judul', name='uq_panduan_kategori_judul')
    )
    with op.batch_alter_table('panduan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panduan_kategori'), ['kategori'], unique=False)

    op.create_table('perisai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radioisotop', sa.String(length=20), nullable=False),
    sa.Column('material_perisai', sa.String(length=20), nullable=False),
    sa.Column('hvl', sa.Float(), nullable=False),
    sa.Column('satuan_hvl', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('radioisotop', 'material_perisai', name='uq_perisai_radioisotop_material')
    )
    with op.batch_alter_table('perisai', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_perisai_material_perisai'), ['material_perisai'], unique=False)
        batch_op.create_index(batch_op.f('ix_perisai_radioisotop'), ['radioisotop'], unique=False)

    op.create_table('radioisotop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radioisotop', sa.String(length=20), nullable=False),
    sa.Column('waktu_paruh', sa.Float(), nullable=False),
    sa.Column('satuan_waktu_paruh', sa.String(length=20), nullable=False),
    sa.Column('konstanta_gamma', sa.Float(), nullable=False),
    sa.Column('satuan_konstanta_gamma', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radioisotop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radioisotop_radioisotop'), ['radioisotop'], unique=True)

    op.create_table('satuan_konversi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jenis_besaran', sa.String(length=50), nullable=False),
    sa.Column('satuan_asal', sa.String(length=30), nullable=False),
    sa.Column('satuan_tujuan', sa.String(length=30), nullable=False),
    sa.Column('faktor_konversi', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jenis_besaran', 'satuan_asal', 'satuan_tujuan', name='uq_satuan_konversi')
    )
    with op.batch_alter_table('satuan_konversi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_satuan_konversi_jenis_besaran'), ['jenis_besaran'], unique=False)
        batch_op.create_index(batch_op.f('ix_satuan_konversi_satuan_asal'), ['satuan_asal'], unique=False)
        batch_op.create_index(batch_op.f('ix_satuan_konversi_satuan_tujuan'), ['satuan_tujuan'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('riwayat_aktivitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('radioisotop', sa.String(length=20), nullable=False),
    sa.Column('aktivitas_awal_input', sa.Float(), nullable=False),
    sa.Column('satuan_awal', sa.String(length=20), nullable=False),
    sa.Column('aktivitas_awal', sa.Float(), nullable=False),
    sa.Column('satuan_hasil', sa.String(length=20), nullable=False),
    sa.Column('tanggal_awal', sa.Date(), nullable=False),
    sa.Column('tanggal_hitung', sa.Date(), nullable=False),
    sa.Column('selang_hari', sa.Integer(), nullable=False),
    sa.Column('waktu_paruh_hari', sa.Float(), nullable=False),
    sa.Column('hasil_aktivitas', sa.Float(), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('riwayat_aktivitas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_riwayat_aktivitas_radioisotop'), ['radioisotop'], unique=False)
        batch_op.create_index(batch_op.f('ix_riwayat_aktivitas_user_id'), ['user_id'], unique=False)

    op.create_table('riwayat_daerah_radiasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pembatas_dosis', sa.Float(), nullable=False),
    sa.Column('jam_kerja', sa.Float(), nullable=False),
    sa.Column('laju_paparan', sa.Float(), nullable=False),
    sa.Column('satuan_paparan', sa.String(length=20), nullable=False),
    sa.Column('laju_paparan_msv', sa.Float(), nullable=False),
    sa.Column('jarak_acuan', sa.Float(), nullable=False),
    sa.Column('satuan_jarak_acuan', sa.String(length=10), nullable=False),
    sa.Column('faktor_okupansi', sa.Float(), nullable=False),
    sa.Column('batas_pengendalian_tahun', sa.Float(), nullable=False),
    sa.Column('batas_supervisi_tahun', sa.Float(), nullable=False),
    sa.Column('batas_pengendalian_jam', sa.Float(), nullable=False),
    sa.Column('batas_supervisi_jam', sa.Float(), nullable=False),
    sa.Column('hasil_pengendalian', sa.Float(), nullable=False),
    sa.Column('hasil_supervisi', sa.Float(), nullable=False),
    sa.Column('estimasi_dosis_tahun', sa.Float(), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('riwayat_daerah_radiasi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_riwayat_daerah_radiasi_user_id'), ['user_id'], unique=False)

    op.create_table('riwayat_paparan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kondisi_perisai', sa.String(length=30), nullable=False),
    sa.Column('radioisotop', sa.String(length=20), nullable=False),
    sa.Column('konstanta_gamma', sa.Float(), nullable=False),
    sa.Column('satuan_konstanta_gamma', sa.String(length=50), nullable=False),
    sa.Column('aktivitas_input', sa.Float(), nullable=False),
    sa.Column('satuan_aktivitas', sa.String(length=20), nullable=False),
    sa.Column('aktivitas', sa.Float(), nullable=False),
    sa.Column('jarak_input', sa.Float(), nullable=False),
    sa.Column('satuan_jarak', sa.String(length=20), nullable=False),
    sa.Column('jarak', sa.Float(), nullable=False),
    sa.Column('material_perisai', sa.String(length=20), nullable=True),
    sa.Column('tebal_perisai_input', sa.Float(), nullable=True),
    sa.Column('satuan_tebal_perisai', sa.String(length=20), nullable=True),
    sa.Column('tebal_perisai', sa.Float(), nullable=True),
    sa.Column('hvl', sa.Float(), nullable=True),
    sa.Column('satuan_hvl', sa.String(length=20), nullable=True),
    sa.Column('laju_paparan', sa.Float(), nullable=False),
    sa.Column('satuan_laju_paparan', sa.String(length=50), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('riwayat_paparan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_riwayat_paparan_radioisotop'), ['radioisotop'], unique=False)
        batch_op.create_index(batch_op.f('ix_riwayat_paparan_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_paparan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_riwayat_paparan_user_id'))
        batch_op.drop_index(batch_op.f('ix_riwayat_paparan_radioisotop'))

    op.drop_table('riwayat_paparan')
    with op.batch_alter_table('riwayat_daerah_radiasi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_riwayat_daerah_radiasi_user_id'))

    op.drop_table('riwayat_daerah_radiasi')
    with op.batch_alter_table('riwayat_aktivitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_riwayat_aktivitas_user_id'))
        batch_op.drop_index(batch_op.f('ix_riwayat_aktivitas_radioisotop'))

    op.drop_table('riwayat_aktivitas')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('satuan_konversi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_satuan_konversi_satuan_tujuan'))
        batch_op.drop_index(batch_op.f('ix_satuan_konversi_satuan_asal'))
        batch_op.drop_index(batch_op.f('ix_satuan_konversi_jenis_besaran'))

    op.drop_table('satuan_konversi')
    with op.batch_alter_table('radioisotop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radioisotop_radioisotop'))

    op.drop_table('radioisotop')
    with op.batch_alter_table('perisai', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_perisai_radioisotop'))
        batch_op.drop_index(batch_op.f('ix_perisai_material_perisai'))

    op.drop_table('perisai')
    with op.batch_alter_table('panduan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panduan_kategori'))

    op.drop_table('panduan')
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faq_kategori'))

    op.drop_table('faq')
    # ### end Alembic commands ###
